export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';


export const STORE_MOVIES = "MOVIES/STORE_MOVIES"
export const CHANGE_RATING = "MOVIES?CHANGE_RATING"
